### GET all in db
GET http://localhost:3000/notes

### GET without keyword
http://localhost:3000/notes

### POST test request
POST http://localhost:3000/notes/ HTTP/1.1
Content-Type: application/json

{
  "id": 6,
  "body": "Also created with REST client.. removed the title tags since I just need a note"
}

