### GET all in db
GET http://localhost:3000/notes

### GET without keyword
http://localhost:3000/notes

### POST test request
POST http://localhost:3000/notes/ HTTP/1.1
Content-Type: application/json

{
  "id": 4,
  "title": "REST Client Note 2",
  "body": "This was also created through RestClient but corrected the mistake I made in id3"
}

